### ISSUE TITLE
The NewebPay decode data error.

### ISSUE THREAD

**Issue by devadev2485** [ycs77/laravel-newebpay#2]
I am getting error in while using notify url 
The NewebPay decode data error.

 public function NewebnotifyUrl(Request $request)
  {
    Storage::put('devadev.txt', NewebPay::decode($request->input('TradeInfo')));
  }

fo this i used get route and configured notify url in .env

Please help me

**Comment by ycs77** [comment]
Sorry, I am not using NewebPay right now, if you have any problem, you can check the [NewebPay API documentation](https://www.newebpay.com/website/Page/content/download_api) or Fork this repo to read source code to solve the problem.
